// Canonical ASF project display names (e.g. "jmeter" -> "Apache JMeter").
//
// The bundled map (apache-projects.json, regenerated by
// scripts/gen-apache-projects.mjs) covers every top-level project. For an
// id missing from the bundle we fall back, in order, to a one-shot live
// fetch of the same feed, then to a capitalize-each-word heuristic — so
// the lookup always returns something sensible, even offline.

import bundled from "./apache-projects.json";

const FEED = "https://projects.apache.org/json/foundation/projects.json";

const names: Record<string, string> = { ...(bundled as Record<string, string>) };
let fetched = false;
let inflight: Promise<void> | null = null;

function capitalizeWords(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

/** Canonical "Apache X" name for a project id, with heuristic fallback. */
export function projectDisplayName(id: string): string {
  if (!id) return "";
  return names[id] ?? `Apache ${capitalizeWords(id)}`;
}

/** Default target-audience sentence for a project, e.g.
 * "Apache JMeter community". Empty string for an empty id. */
export function audienceFor(id: string): string {
  return id ? `${projectDisplayName(id)} community` : "";
}

/** True when the bundled/fetched map has an authoritative name for `id`. */
export function isKnownProject(id: string): boolean {
  return id in names;
}

/**
 * Lazily fetch the canonical feed once to fill in names for ids missing
 * from the bundled map. Resolves when done (or immediately if already
 * fetched). Never throws: on network/CORS/parse failure the bundled map
 * plus heuristic remain in effect.
 */
export async function ensureProjectNames(): Promise<void> {
  if (fetched) return;
  if (inflight) return inflight;
  inflight = (async () => {
    try {
      const res = await fetch(FEED);
      if (!res.ok) return;
      const data = (await res.json()) as Record<string, { name?: string }>;
      for (const [id, value] of Object.entries(data)) {
        if (value && typeof value.name === "string") names[id] = value.name;
      }
      fetched = true;
    } catch {
      // offline / CORS / parse error: keep bundled names + heuristic.
    } finally {
      inflight = null;
    }
  })();
  return inflight;
}
